#!/bin/sh
echo Installing PKGS
echo Using default config
pkgs_home="/etc/pkgs-home"
item_config="/etc/pkgs-home/items"
dest="/usr/local/bin"
cache="/etc/pkgs-home/cache"
backup_dir="/etc/pkgs-home/backup"
mkdir $pkgs_home
mkdir $item_config
mkdir $cache
mkdir $backup_dir
mkdir $item_config/repos
mkdir $backup_dir/items
mkdir $backup_dir/config
cd $pkgs_home
curl -o pkgsconf https://raw.githubusercontent.com/Pan00Pernicek/scriptpkg/v2/pkgsconf
cd $dest
curl -o pkgs https://raw.githubusercontent.com/Pan00Pernicek/scriptpkg/v2/pkgs
chmod +x pkgs
pkgs repo-add https://raw.githubusercontent.com/Pan00Pernicek/scriptpkg/v2/repos/repotest main 
echo done!!!
