#!/bin/sh
##feature config
download_method=curl
	##avaible:
		#curl
		#wget (wip)
backup=yes
backup_time=300 #seconds #wip #not implemented yet!!!
raw_output=no
##directory definitions
pkgs_home=~/.config/pkgs-home
item_config="$pkgs-home/items"
dest="/usr/local/bin"
cache="$pkgs-home/cache"
backup_dir="$pkgs-home/backup"
##usage
#pkgs fn_exec is non-changeable due to its need for scriping support
user_install="install"
user_update="update"
user_remove="remove"
user_backup_clear="clear"
user_install_raw="sync"
user_add_repo="repo-add"
user_remove_repo="repo-remove"
user_list="list"
user_repo_list="repo-list"
user_search="search"
##debug
debug=no
compress_bin=no
compress_backup=no
compress_method=xz
