#!/bin/sh
if [ -z "$1" ];then
 spkg help
 exit
fi
pkgdir=$(cat ~/.config/spkg/destination)
if [ $1 = sync ]; then
 if [ $2 = file ]; then
  pkgurl=$3
  dest=$4
  pkgname=$(basename $dest)
  cd $(dirname $dest)
  #wget -O $(basename $dest) $pkgurl
  curl $pkgurl -o $(basename $dest)
  echo make file executable y/n ?
  read execque
  if [ $execque = y ]; then
   echo $(tput setaf 5) "Making script executable:"$(tput setaf 8)"chmod +x $pkgname"$(tput sgr0)
   chmod +x $pkgname
  fi
  echo $(tput setaf 6) "Adding config file:"$(tput setaf 8)"at config pkg dir:touch $pkgname:add url & dir to it"$(tput sgr0)
  cd ~/.config/spkg/packages
  touch $pkgname
  echo $pkgurl"/url" > $pkgname
  echo $dest"/destination" >> $pkgname
  echo $(tput setaf 2) "Done!" $(tput sgr0)
 else
  if [ -z "$3" ]; then
   pkgurl=$2
   echo What is the name that you want to call that script"("suggested: $(basename $pkgurl)")"?
   read pkgname
   spkg sync $pkgurl $pkgname
  else
   pkgurl=$2
   pkgname=$3
   cd $pkgdir
   curl $pkgurl -o $pkgname
   echo $(tput setaf 5) "Making script executable:"$(tput setaf 8)"chmod +x $pkgname"$(tput sgr0)
   chmod +x $pkgname
   echo $(tput setaf 6) "Adding config file:"$(tput setaf 8)"at config pkg dir:touch $pkgname:add url to it"$(tput sgr0)
   cd ~/.config/spkg/packages
   touch $pkgname
   echo $pkgurl"/url" > $pkgname
   echo $(tput setaf 2) "Done!" $(tput sgr0)
  fi
 fi
elif [ $1 = update ]; then
 pkgname=$2
 cd $pkgdir
 if [ -f ~/.config/spkg/packages/$pkgname ]; then
  if [ $(head -n $pkgname) = "#spkg appconf" ]; then
   echo custom config detected, using it: bash $pkgname
   bash $pkgname
  else
   echo $(tput setaf 6) "Getting script config:"$(tput setaf 8)"spkg catconf $pkgname"$(tput sgr 0)
   pkgurl=$(spkg catconf $pkgname)
   spkg sync  $(dirname $(spkg catconf $pkgname | grep url)) $pkgname $(dirname $(spkg catconf $pkgname | grep destination))
  fi
 else
  echo $(tput setaf 1)Sorry, but package does not exist.$(tput sgr0)
 fi
elif [ $1 = remove ]; then
 pkgname=$2
 echo $(tput setaf 1) "Removing script:"$(tput setaf 8)"if not custom dir cd to pkg dir -> rm $pkgname:else cd to $pkgfiledir -> rm $pkgfile"$(tput sgr0)
 if [ -z $(dirname $(spkg catconf $pkgname | grep destination)) ]; then
  cd $pkgdir
  rm $pkgname
 else
  pkgfiledir=$(dirname $(dirname $(spkg catconf $pkgname | grep destination)))
  pkgfile=$(basename $(dirname $(spkg catconf $pkgname | grep destination)))
  cd $pkgfiledir
  rm $pkgfile
 fi
  echo $(tput setaf 1) "Removing script config:"$(tput setaf 8)"at pkg config dir -> rm $pkgname"$(tput sgr0)
  cd ~/.config/spkg/packages
  rm $pkgname
elif [ $1 = list ]; then
 ls ~/.config/spkg/packages
elif [ $1 = install ]; then
 pkgname=$2
 cd ~/.config/spkg/
 if [ -z $3 ]; then 
  echo select repo "("options: $(ls repos)")"
  read pkginrepo
 else
  pkginrepo=$3
 fi
 curl $(cat repos/$pkginrepo) -o repo
 echo $(tput setaf 6) "Executing repo index:"$(tput setaf 8)"+x & bash repo $pkgname $4"$(tput sgr0)
 chmod +x repo
 bash repo $pkgname $4
 echo $(tput setaf 1) "Removing repo index:"$(tput setaf 8)"repo -> rm"$(tput sgr0)
 rm repo
elif [ $1 = repo ]; then
 if [ $2 = add ]; then
  pkgrepo=$3
  cd ~/.config/spkg/repos
  echo What is the name that you want to call that repo"("suggested: $(basename $pkgrepo)")"?
  read pkgreponame
  touch $pkgreponame
  echo $pkgrepo > $pkgreponame
  echo $(tput setaf 2) "Added repo $pkgreponame with address $pkgrepo!" $(tput sgr0)
 elif [ $2 = remove ]; then
  pkgrmrepo=$3
  cd ~/.config/spkg/repos
  rm $pkgrmrepo
 elif [ $2 = getcore ]; then
  echo Current core repos:
  curl -s https://raw.githubusercontent.com/Pan00Pernicek/scriptpkg/master/repo-index
  echo add one by: spkg repo add repo-url
 elif [ $2 = list ]; then
  ls ~/.config/spkg/repos
 else
 echo invalid repo option!
 fi
elif [ $1 = catconf ]; then
 if [ $2 = destination ]; then
  cat ~/.config/spkg/destination
 else
  cat ~/.config/spkg/packages/$2
 fi
elif [ $1 = spkg-s ]; then
 mkdir /tmp/spkgrepo
 cd /tmp/spkgrepo
 touch $2
 echo $3 > $2
elif [ $1 = spkg-g ]; then
 cd /tmp/spkgrepo
 cat $2
elif [ $1 = confget ]; then
 echo url=$(dirname $(spkg catconf $2 | grep url)) 
 echo destination=$(dirname $(spkg catconf $2 | grep destination))
elif [ $1 = search ]; then
 pkgname=$2
 cd ~/.config/spkg/
 if [ -z $3 ]; then 
  echo select repo "("options: $(ls repos)")"
  read pkginrepo
 else
  pkginrepo=$3
 fi
 curl $(cat repos/$pkginrepo) -o repo
 cat repo | grep $pkgname
else
 echo $(tput setaf 4) https://raw.githubusercontent.com/Pan00Pernicek/scriptpkg/master/usage $(tput sgr0)
 curl -s https://raw.githubusercontent.com/Pan00Pernicek/scriptpkg/master/usage
fi
